"""
Validate all 6 trained classifiers against Claude Opus-labeled B2B sales conversations.

This is the "frontier model validation" — if our classifiers (trained on academic datasets)
agree with Claude's labels 80%+ of the time, that's strong evidence of quality without
circularity (Claude didn't generate the training data).
"""
import sys, os, json
os.environ["PYTHONIOENCODING"] = "utf-8"
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from collections import Counter

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")


def load_validation_data():
    """Load both validation set files."""
    all_turns = []
    for fname in ["claude_validation_set.json", "claude_validation_set_2.json"]:
        path = os.path.join(DATA_DIR, fname)
        with open(path, "r", encoding="utf-8") as f:
            convs = json.load(f)
        for conv in convs:
            outcome = conv.get("outcome")
            for i, turn in enumerate(conv["turns"]):
                all_turns.append({
                    "text": turn["text"],
                    "speaker": turn["speaker"],
                    "labels": turn["labels"],
                    "conv_id": conv["conversation_id"],
                    "turn_idx": i,
                    "outcome": outcome,
                })
    return all_turns


def main():
    print("=" * 70)
    print("FRONTIER MODEL VALIDATION: Claude Opus Labels vs Trained Classifiers")
    print("=" * 70)
    print("\nLabels generated by Claude Opus 4.6 (frontier model)")
    print("Classifiers trained on academic datasets (no Claude data in training)")
    print("Agreement = evidence of classifier quality without circularity\n")

    turns = load_validation_data()
    print(f"Loaded {len(turns)} labeled turns from {len(set(t['conv_id'] for t in turns))} conversations\n")

    # Load classifiers
    from training.inference import (
        predict_objection, predict_handling, predict_emotion,
        predict_outcome, predict_sales_state, predict_willingness,
    )

    results = {
        "objection_type": {"correct": 0, "total": 0, "details": []},
        "handling": {"correct": 0, "total": 0, "details": []},
        "emotion": {"correct": 0, "total": 0, "details": []},
        "pressure": {"correct": 0, "total": 0, "details": []},
        "sales_state": {"correct": 0, "total": 0, "details": []},
        "willingness": {"correct": 0, "total": 0, "details": []},
        "outcome": {"correct": 0, "total": 0, "details": []},
    }

    # Build conversation windows for state/willingness (last 3 turns)
    conv_turns = {}
    for t in turns:
        cid = t["conv_id"]
        if cid not in conv_turns:
            conv_turns[cid] = []
        conv_turns[cid].append(t)

    for turn in turns:
        text = turn["text"]
        labels = turn["labels"]
        cid = turn["conv_id"]
        tidx = turn["turn_idx"]

        # ── Objection Type ──
        claude_obj = labels.get("objection_type")
        if claude_obj:
            pred = predict_objection(text)
            # Simplify: both "not_objection" or both some objection type
            claude_is_obj = claude_obj != "not_objection"
            pred_is_obj = pred["is_objection"]
            match = claude_is_obj == pred_is_obj
            results["objection_type"]["total"] += 1
            if match:
                results["objection_type"]["correct"] += 1
            results["objection_type"]["details"].append({
                "text": text[:60], "claude": claude_obj, "pred": pred["label"], "match": match
            })

        # ── Handling ──
        claude_handling = labels.get("handling")
        if claude_handling and tidx > 0:
            prev_turns = conv_turns[cid]
            if tidx > 0:
                prev_text = prev_turns[tidx - 1]["text"]
                pred = predict_handling(prev_text, text)
                match = claude_handling == pred["label"]
                results["handling"]["total"] += 1
                if match:
                    results["handling"]["correct"] += 1
                results["handling"]["details"].append({
                    "text": text[:60], "claude": claude_handling, "pred": pred["label"], "match": match
                })

        # ── Emotion ──
        claude_emotion = labels.get("emotion")
        if claude_emotion and claude_emotion in ("positive", "negative", "neutral", "empathetic", "anxious"):
            pred = predict_emotion(text)
            match = claude_emotion == pred["label"]
            results["emotion"]["total"] += 1
            if match:
                results["emotion"]["correct"] += 1
            results["emotion"]["details"].append({
                "text": text[:60], "claude": claude_emotion, "pred": pred["label"], "match": match
            })

        # ── Pressure ──
        claude_pressure = labels.get("pressure")
        if claude_pressure and claude_pressure in ("consultative", "urgent", "demanding"):
            pred = predict_emotion(text)  # Same model detects pressure
            if pred["is_pressure"]:
                pred_pressure = pred["pressure_type"]
            else:
                pred_pressure = "consultative"  # default if no pressure detected
            match = claude_pressure == pred_pressure
            results["pressure"]["total"] += 1
            if match:
                results["pressure"]["correct"] += 1
            results["pressure"]["details"].append({
                "text": text[:60], "claude": claude_pressure, "pred": pred_pressure, "match": match
            })

        # ── Sales State ──
        claude_state = labels.get("sales_state")
        if claude_state:
            # Merge comparison → evaluation (model was trained without comparison)
            if claude_state == "comparison":
                claude_state = "evaluation"
            # Build window text
            window_start = max(0, tidx - 2)
            window = conv_turns[cid][window_start:tidx + 1]
            window_text = " ".join([f"{t['speaker']}: {t['text']}" for t in window])
            pred = predict_sales_state(window_text[:512])
            match = claude_state == pred["state"]
            results["sales_state"]["total"] += 1
            if match:
                results["sales_state"]["correct"] += 1
            results["sales_state"]["details"].append({
                "text": text[:60], "claude": claude_state, "pred": pred["state"], "match": match
            })

        # ── Willingness ──
        claude_will = labels.get("willingness")
        if claude_will:
            window_start = max(0, tidx - 2)
            window = conv_turns[cid][window_start:tidx + 1]
            window_text = " ".join([f"{t['speaker']}: {t['text']}" for t in window])
            pred = predict_willingness(window_text[:512])
            match = claude_will == pred["level"]
            results["willingness"]["total"] += 1
            if match:
                results["willingness"]["correct"] += 1
            results["willingness"]["details"].append({
                "text": text[:60], "claude": claude_will, "pred": pred["level"], "match": match
            })

    # ── Outcome Predictor (conversation-level) ──
    for cid, ctns in conv_turns.items():
        outcome = ctns[0]["outcome"]
        if outcome is not None:
            conv_text = " ".join([f"{t['speaker']}: {t['text']}" for t in ctns])
            pred = predict_outcome(conv_text[:512])
            pred_outcome = 1 if pred["label"] == "converted" else 0
            match = outcome == pred_outcome
            results["outcome"]["total"] += 1
            if match:
                results["outcome"]["correct"] += 1
            results["outcome"]["details"].append({
                "conv": cid, "claude": outcome, "pred": pred_outcome,
                "prob": pred["probability"], "match": match
            })

    # ── Print Results ──
    print("=" * 70)
    print("AGREEMENT RESULTS: Claude Opus Labels vs Trained Classifiers")
    print("=" * 70)
    print()

    overall_correct = 0
    overall_total = 0

    for task, data in results.items():
        total = data["total"]
        correct = data["correct"]
        if total == 0:
            continue
        pct = correct / total * 100
        status = "PASS" if pct >= 70 else "MARGINAL" if pct >= 50 else "FAIL"
        print(f"  {task:20s}: {correct:3d}/{total:3d} = {pct:5.1f}% agreement  [{status}]")
        overall_correct += correct
        overall_total += total

        # Show mismatches
        mismatches = [d for d in data["details"] if not d["match"]]
        if mismatches and len(mismatches) <= 5:
            for m in mismatches[:3]:
                text_key = "text" if "text" in m else "conv"
                print(f"    MISS: claude={m['claude']}, pred={m['pred']} | {m[text_key]}")

    print()
    overall_pct = overall_correct / overall_total * 100 if overall_total > 0 else 0
    print(f"  {'OVERALL':20s}: {overall_correct:3d}/{overall_total:3d} = {overall_pct:5.1f}% agreement")
    print()

    if overall_pct >= 80:
        print("  VERDICT: STRONG — classifiers agree with frontier model 80%+ of the time")
    elif overall_pct >= 70:
        print("  VERDICT: GOOD — classifiers show substantial agreement with frontier model")
    elif overall_pct >= 60:
        print("  VERDICT: MODERATE — classifiers partially align with frontier model")
    else:
        print("  VERDICT: WEAK — significant disagreement with frontier model")

    print()
    print("  This validation is non-circular: Claude Opus generated the labels,")
    print("  but NO Claude data was used in classifier training.")
    print("  Training sources: CaSiNo (NAACL 2021), GoEmotions (ACL 2020),")
    print("  ESConv (ACL 2021), dair-ai/emotion, DeepMost SaaS, DialogStudio SalesBot")


if __name__ == "__main__":
    main()
